apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
        - image: pull ghcr.io/2023-4400-exp/4417-go-server-ci:f3b92e61ef5a5d7a4d3a5d48c5d51df008868376@sha256:41f0e5488cb058c8319c77e987a56195ea8faaed6862fce267585ee7ef36b6e8
        name: go-server-ci

